# difference between MapInfo and Map:
# MapInfo is a resource generated by the serverside and received by the client used clientside and contains important metadata, objects and players in the map
# Map is a 3d node used serverside purely for metadata and objects and does not contain the players (interactions are handled by server/map.gd)

extends Resource

class_name MapInfo

var serverVersion: String
var name: String
var author: String
var roundTimer: Timer
var mapObjs: Node3D
var players: Array[PlayerInfo]
var currentPScore: int
var currentYScore: int
