# difference between MapInfo and Map:
# MapInfo is a resource generated by the serverside and received by the client used clientside and contains important metadata, objects and players in the map
# Map is a 3d node used serverside purely for metadata and objects and does not contain the players (interactions are handled by server/map.gd)

class_name MapInfo

## map name. displayed in the ui
var name: String
## map author. can be real name, nickname or github username
var author: String
## map timer
var roundTimer: Timer
## node containing all the objects in the map
var mapObjs: Node3D
## list of players, with each player described with `PlayerInfo`
var players: Array[PlayerInfo]
## the current score for the purple team
var currentPScore: int
## the current score for the yellow team
var currentYScore: int
